export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const CREATE_TODO = 'CREATE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const MARK_COMPLETE_ALL_TODOS = 'MARK_COMPLETE_ALL_TODOS';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_COMPLETED_TODOS = 'DELETE_COMPLETED_TODOS';
export const EDIT_TODO = 'EDIT_TODO';


export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETE: 'SHOW_COMPLETE',
  SHOW_INCOMPLETE: 'SHOW_INCOMPLETE'
};
